version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "SAM-apispec"
s3_bucket = "dev-nezaki"
s3_prefix = ""
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
